# version: '3.8'

# services:
#   backend:
#     image: kanthima005/backend:v1
#     ports:
#       - "3000:3000"
#     restart: always

version: '3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
    - ./config:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock